added intro slides to splash screen UI
CodingIndia/travel-safe pull request #61
Opened 2020-04-21 12:54 UTC by sanxy

Resolved #52

2020-04-21 12:57 UTC, sanxy commented
![Screenshot_20200421-134741](https://user-images.githubusercontent.com/15203737/79868425-c84e3f80-83d7-11ea-85c3-b051c840cc1d.jpg)
![Screenshot_20200421-134755](https://user-images.githubusercontent.com/15203737/79868452-d4d29800-83d7-11ea-84fa-fc9789bb3489.jpg)
![Screenshot_20200421-134804](https://user-images.githubusercontent.com/15203737/79868484-e025c380-83d7-11ea-977a-ccd88c4e8bee.jpg)
![Screenshot_20200421-134809](https://user-images.githubusercontent.com/15203737/79868511-ea47c200-83d7-11ea-9cc3-69b96d56292c.jpg)
![Screenshot_20200421-134816](https://user-images.githubusercontent.com/15203737/79868547-f6cc1a80-83d7-11ea-8b72-7048fa35378e.jpg)
![Screenshot_20200421-134822](https://user-images.githubusercontent.com/15203737/79868600-09465400-83d8-11ea-8313-c0ea6f653c2f.jpg)

2020-04-21 18:32 UTC, tanmayrauth commented
@sanxy We don't need the first screen anymore.
1. Just keep 3 screen
2. Make back and next button similar to example
3. Please make some aesthetic improvements. Since it is first screen all impression about the app is dependent on this 
4. Make use of material design

2020-04-21 18:33 UTC, tanmayrauth reviewed
@sanxy We don't need the first screen anymore.
1. Just keep 3 screen
2. Make back and next button similar to example
3. Please make some aesthetic improvements. Since it is first screen all impression about the app is dependent on this 
4. Make use of material design

2020-04-21 18:37 UTC, ankitshaw approved these changes

2020-04-21 18:40 UTC, ankitshaw requested changes

2020-04-21 18:40 UTC, ankitshaw commented on components/lib/main.dart
>                fontWeight: FontWeight.bold,
as @tanmayrauth need to be removed, we don't need this now

2020-04-21 22:27 UTC, sanxy commented
![Screenshot_20200421-231001](https://user-images.githubusercontent.com/15203737/79920109-982e8d00-8427-11ea-9f37-19958744b6b3.jpg)
![Screenshot_20200421-231009](https://user-images.githubusercontent.com/15203737/79920154-a1b7f500-8427-11ea-8fc4-ffc2e7620ada.jpg)
![Screenshot_20200421-231013](https://user-images.githubusercontent.com/15203737/79920200-a9779980-8427-11ea-97c7-6e929256c8d0.jpg)

2020-04-22 13:19 UTC, tanmayrauth commented
Please increase the padding of the text horizontally. Refer the example. Also keep it 1-2 liner not more than that otherwise no one will read it.
Sorry but the bottom button and structure is still on inline with the example. 

Also make use of gradient colour overlay texture for background like this example
![image](https://user-images.githubusercontent.com/18233626/79986589-eb591c00-84c9-11ea-90a1-d5bea9c3b44a.png)

2020-04-22 13:19 UTC, tanmayrauth commented
@sanxy I appreciate you efforts for rapid development on changes suggested. Kudos to you.

2020-04-22 14:21 UTC, ankitshaw requested changes

2020-04-22 14:21 UTC, ankitshaw commented on components/lib/screens/introPage.dart
> +            fontFamily: 'Raleway'),
Don't use italic style keep it minimalistic.

2020-04-22 14:21 UTC, ankitshaw commented on components/lib/screens/introPage.dart
> +        pathImage: "images/phone.png",
try with open san  for the header and roboto for content text.. if possible keep the content small. 
@tanmayrauth  we may have to decide the content

2020-04-23 19:03 UTC, sanxy commented
![Screenshot_20200423-200057](https://user-images.githubusercontent.com/15203737/80138838-5fb0bf80-859d-11ea-8b76-e0a5f10060c9.jpg)
![Screenshot_20200423-200103](https://user-images.githubusercontent.com/15203737/80138857-69d2be00-859d-11ea-921d-d3c21681c1fe.jpg)
![Screenshot_20200423-200109](https://user-images.githubusercontent.com/15203737/80138883-71926280-859d-11ea-9d08-4c3a01e0f2c2.jpg)

2020-04-24 04:30 UTC, tanmayrauth commented
1. Please make first screen colour like this ![image](https://user-images.githubusercontent.com/18233626/79986589-eb591c00-84c9-11ea-90a1-d5bea9c3b44a.png)

2. Choose some different colour for other 2 screens even.
3. choose some different technology image as logo.
4. For location logo give make with location image.
5. Horizontal line above the button just like example is missing.

2020-04-24 17:46 UTC, tanmayrauth commented
can you give screenshots?

2020-04-24 18:38 UTC, sanxy commented
![Screenshot_20200424-193648](https://user-images.githubusercontent.com/15203737/80245712-1460e480-8663-11ea-9448-a6c7bb7b1787.jpg)
![Screenshot_20200424-193655](https://user-images.githubusercontent.com/15203737/80245735-23e02d80-8663-11ea-9cc7-e0eb6df92774.jpg)
![Screenshot_20200424-193703](https://user-images.githubusercontent.com/15203737/80245747-2b9fd200-8663-11ea-978c-6180fa9ca766.jpg)

2020-04-24 18:41 UTC, tanmayrauth commented
1. technology still needs a change
2. horizontal line missing as example
3. last screen should have 2 button pointing to Login and signup UI.
4. Make last screen a bit more greener

2020-04-26 14:49 UTC, tanmayrauth commented
@sanxy did you got chance for getting the changes done?

2020-04-26 16:55 UTC, sanxy commented
Not yet

2020-04-29 15:27 UTC, sanxy commented
![Screenshot_20200429-162606](https://user-images.githubusercontent.com/15203737/80614328-3a590100-8a36-11ea-8441-a3382a165a8c.jpg)
![Screenshot_20200429-162611](https://user-images.githubusercontent.com/15203737/80614360-45ac2c80-8a36-11ea-9d39-59daea188620.jpg)
![Screenshot_20200429-162618](https://user-images.githubusercontent.com/15203737/80614380-4cd33a80-8a36-11ea-9b68-19bd6e158ba7.jpg)

2020-04-29 15:29 UTC, tanmayrauth commented
All looks good. Just register button should be at left and since the register ui is there in place can you add event to open register UI.

2020-04-29 15:30 UTC, tanmayrauth commented
> All looks good. Just register button should be at left and since the register ui is there in place can you add event to open register UI.

Once this is done we will get it merged

2020-04-29 16:41 UTC, sanxy commented
Register button opens the Register page, its already added. I must point out there is an import in the Register page which is not used which should be deleted.

2020-04-29 17:06 UTC, sanxy commented
![Screenshot_20200429-180457](https://user-images.githubusercontent.com/15203737/80624795-17cde480-8a44-11ea-95d3-2c041391c189.jpg)
![Screenshot_20200429-180514](https://user-images.githubusercontent.com/15203737/80624823-21574c80-8a44-11ea-9f8a-829cbc81fcb9.jpg)

2020-04-29 17:29 UTC, tanmayrauth commented
@sanxy I meant like how login button was at extreme right.
Similarly Register button should be at left

Taking example of skip button in technology screen

2020-04-29 17:46 UTC, sanxy commented
![Screenshot_20200429-184535](https://user-images.githubusercontent.com/15203737/80628727-b90b6980-8a49-11ea-9200-f94a144333bf.jpg)

2020-04-30 15:43 UTC, ankitshaw approved these changes

2020-04-30 15:47 UTC, ankitshaw commented
@sanxy  there is merge conflict. can you please pull he latest updates to the development branch and push your branch again.  Make sure nothing breaks.

2020-05-01 00:08 UTC, closed without merging