An activity with all helpline number
CodingIndia/travel-safe pull request #62
Opened 2020-04-21 19:34 UTC by akshaysingh5

2020-04-21 19:45 UTC, tanmayrauth commented
please provide screenshots and all checks are not passing

2020-04-21 20:39 UTC, akshaysingh5 commented
![Helplineinfo](https://user-images.githubusercontent.com/51755727/79911479-0e3dee80-843e-11ea-836f-b86f7e277c47.jpg)

**sir, i Don't know why this all checks error comes**

2020-04-22 13:30 UTC, tanmayrauth commented
@ankitshaw @pravinyo can you guys check on this ?

2020-04-22 16:16 UTC, ankitshaw requested changes
UI needs improvement. Use fonts Open sans for header and roboto for content . Use material design principles.  For example.
![image](https://user-images.githubusercontent.com/25771394/80006347-61697d00-84e2-11ea-9143-67498bec6c3c.png)

2020-04-22 16:16 UTC, ankitshaw commented on master/lib/helpline.dart
> +      ),
use Open sans for header and Roboto for content.

2020-04-22 16:18 UTC, ankitshaw commented on master/lib/helpline.dart
> +      ),
card layout is needed keeping in mind further features

2020-04-26 11:46 UTC, tanmayrauth commented
@akshaysingh5 any update over changes suggested by @ankitshaw ?

2020-04-29 14:25 UTC, ankitshaw commented
closing this due to inactivity

2020-04-29 14:25 UTC, closed without merging