Fixed the Google icon on Login page
CodingIndia/travel-safe pull request #74
Opened 2020-05-04 15:18 UTC by akshaysingh5

![loginUIchanges](https://user-images.githubusercontent.com/51755727/80982184-9661c200-8e48-11ea-93cf-ef187e7117c6.png)

2020-05-05 12:54 UTC, akshaydhiran reviewed
![NewUpdatedLoginScreen](https://user-images.githubusercontent.com/51755727/81068175-8c4dcb00-8efd-11ea-8d65-735421906b7d.jpg)

2020-05-05 14:26 UTC, TahaAli07 reviewed
@akshaysingh5 We can delete the Facebook and Google icon files now.

2020-05-05 14:46 UTC, akshaysingh5 commented
Okay

2020-05-05 14:47 UTC, ankitshaw requested changes
I feel the logo looks too small and the gap between login button and signup line is large.

2020-05-05 14:49 UTC, akshaysingh5 commented
@ankitshaw  Okay, I will make the changes now and update you on slack first.

2020-05-05 16:01 UTC, akshaydhiran reviewed
![LastUpdatedLoginScreen](https://user-images.githubusercontent.com/51755727/81087561-8238c600-8f17-11ea-8d74-1d51e66c5a53.jpg)

&


![LoginScreen](https://user-images.githubusercontent.com/51755727/81087839-ce840600-8f17-11ea-9d82-77927cc69de5.jpg)

2020-05-05 17:18 UTC, akshaysingh5 commented
1st Image is for when we have vertical: 10 on line no. 180 ( Login.dart ).
2nd images is for when we have vertical: 100 on line no. 180 ( Login.dart ).

2020-05-05 18:44 UTC, ankitshaw approved these changes

2020-05-05 18:44 UTC, ankitshaw commented on master/lib/screens/login.dart
> +          SizedBox(height: 80),
need for this change?

2020-05-05 18:44 UTC, merged

2020-06-07 11:19 UTC, ankitshaw commented
@all-contributors bot please add @akshaysingh5  for fix

2020-06-07 11:19 UTC, ankitshaw commented
@all-contributors bot please add @akshaysingh5  for code